import { Ubuntu } from "next/font/google"
import 'bootstrap/dist/css/bootstrap.css'
import 'bootstrap-icons/font/bootstrap-icons.css'
import './globals.css'
import Script from "next/script"
import LoaderPage from "@/loaderPage"


const ubuntu = Ubuntu({
  subsets : ['latin'],
  weight: ['500', '700']
}) 


export const metadata = {
  title: 'GearBoost',
  description: 'Generated by Next.js',
}

export default function RootLayout({children,}: {children: React.ReactNode}) {

  return (
    <html lang="fr">
      <body className={ubuntu.className}>
        <div style={{ minHeight: "100vh", overflow: "visible" }}>
          <main>
            <LoaderPage>
              {children}
            </LoaderPage>
          </main>
        </div>
        <Script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.js"
          strategy="afterInteractive"
        />
      </body>
    </html>
  )
}
